### ISSUE TITLE
Web UI: "Assign network IP address" is confusing

### ISSUE THREAD

**Issue by jasaw** [DiUS/build-lights#5]
The description "Assign network IP address" is confusing. We always want to assign an IP address to the Pi. Question is whether the IP address is assigned via DHCP, or assigned manually.

**Comment by tarciosaraiva** [comment]
Fair point @jasaw . I guess "Manually assign IP address" makes more sense?

**Comment by jasaw** [comment]
What about "IP address assignment" and the choices are "Static (manual)" and "DHCP (dynamic)"?

**Comment by tarciosaraiva** [comment]
Yup, like it. Doing it.

**Comment by tarciosaraiva** [comment]
fixed by latest commit https://github.com/DiUS/build-lights/commit/25d448039adc6e525b0db2be376894c57070ac29
